"""empty message

Revision ID: 703cdb17a49f
Revises: 89ac610b1b40
Create Date: 2020-11-26 02:39:47.657236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703cdb17a49f'
down_revision = '89ac610b1b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=250)),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.ARRAY(sa.String(length=250)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
